# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsOW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(OtherWindow)
        self.pushButton.setGeometry(QtCore.QRect(30, 180, 301, 91))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "Dialog"))
        self.pushButton.setText(_translate("OtherWindow", "в пизду"))
